a = input("digite algo :")
print("o tipo primitivo desse valor é", type(a))
print("contem espaços?",a.isspace())
print("contem alfanumericos?",a.isalnum())
print("é alfabetico?",a.isalpha())
print("contem numeros e letras?",a.isidentifier())
print("contem um numero?",a.isnumeric())
print("contem letra maiscula?",a.isupper())
print("contem letras minusculas?",a.islower())
print("esta capitalizada?",a.istitle())